### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by underlaw** [simcu/headscale-ui#1]
![image](https://user-images.githubusercontent.com/33020405/227452044-a3d36067-3cfe-4b80-b6f5-0d1b812769b3.png)

![image](https://user-images.githubusercontent.com/33020405/227451554-239afaef-f70b-42db-878e-a80d299fdcc7.png)

![image](https://user-images.githubusercontent.com/33020405/227451941-168ce552-fbe8-4250-b245-72ab327f1b99.png)

**Comment by xrain0610** [comment]
are you use docker?

404 that is error about serverUrl.
 on login page , change serverUrl
