### ISSUE TITLE
Issue connecting to headscale server

### ISSUE THREAD

**Issue by ithakaa** [simcu/headscale-ui#4]
I might be making a mistake somewhere because I'm having trouble figuring out where to begin troubleshooting. Initially, I successfully set up a headscale server, and everything appears to be functioning smoothly as I have established connections with nodes without any problems.

However, my current challenge involves setting up headscale-ui. I generated an API key, but when I enter the server address (http://headscale.mydomain.tld) and provide the key, I encounter an error.

[object ProgressEvent]

The firewall is disabled and I'm just using a default Apache server with a static website defined on port 80

Aside from generating an API key, do I need to do anything else with the headscale server to allow access ?

If anyone can help, it would be greatly appreciated

**Comment by Roodborst** [comment]
Same issue on here. Screenshots looks good. Like to try-out.

**Comment by Cloudy-Kumori** [comment]
Do you fix the problem now? I got the same issue, and I need some help, thank you!

**Comment by ithakaa** [comment]
> Do you fix the problem now? I got the same issue, and I need some help, thank you!

Have a look here
https://github.com/ithakaa/headscale-ui-npm

**Comment by Cloudy-Kumori** [comment]
> > Do you fix the problem now? I got the same issue, and I need some help, thank you!
> 
> Have a look here https://github.com/ithakaa/headscale-ui-npm

Thank you for your reply. I have read your repository carefully, but I'm wondering whether I can just use NGINX to set up a static website (just like in Deploy Guide A) without using Docker? I'm not sure which step I made a mistake in, so I used the F12 browser developer tool to check the connection between my computer and the headscale server, and I found that the headscale server URL gave me a "401 Unauthorized" response. Is there something wrong with my NGINX configuration, or do I really need to use the "reverse proxy" feature to make the headscale UI work?

Sorry for asking so many questions. I'm a beginner at learning NGINX, so it's quite confusing to me. I would appreciate it if you could give me some advice on this. Sorry for taking your time, and I wish you have a good day!
