### ISSUE TITLE
Install ui for debian

### ISSUE THREAD

**Issue by SebastienSueurDamie** [simcu/headscale-ui#6]
Good morning,

I would like to install headscale-ui on a debian server but there is no indication on the installation to follow. Has anyone already done this installation or can help me with it?

Thanks

**Comment by xrain0610** [comment]
this project is only a static web project, so it can run anywhere ,only need a webserver , like nginx etc.

**Comment by DanHolli** [comment]
```
sudo apt install nginx wget unzip
wget [insert url to zip release]
unzip [insert zip filename]
sudo cp -r ./headscale-ui/ /var/www/html/
sudo mv /var/www/html/index.nginx-debian.html /var/www/html/nginx-debian.html
```
make any edits to /etc/nginx/sites-available/default
```
sudo systemctl restart nginx
```
